In [1]:
import pandas as pd
import numpy as np
from sodapy import Socrata
import matplotlib.pyplot as plt 
import scipy.stats as stats
import re

%matplotlib inline

In [3]:

# client = Socrata('data.seattle.gov',
#                   app_token='h5vKraDOpWIZy3vvPhZ6hBQab')

# results = client.get('tmmm-ytt6', select='*', where='checkoutyear=2020', limit = 10000000)

In [ ]:
library_2020_all =pd.DataFrame.from_records(results)

In [5]:
library_2020_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 639821 entries, 0 to 639820
Data columns (total 11 columns):
checkoutmonth      639821 non-null object
checkouts          639821 non-null object
checkouttype       639821 non-null object
checkoutyear       639821 non-null object
creator            567397 non-null object
materialtype       639821 non-null object
publicationyear    638950 non-null object
publisher          638986 non-null object
subjects           636544 non-null object
title              639821 non-null object
usageclass         639821 non-null object
dtypes: object(11)
memory usage: 53.7+ MB

In [8]:
library_2020_all = pd.read_csv('~/galvanize/capstone/capstone_one/llibrary_2020_all.csv', index_col=0)

In [9]:
library_2020_all = library_2020_all.astype({'checkouts':'int64','publicationyear': 'str', 'subjects': 'str', 'title':'str', 'creator':'str'}, inplace=True)

In [13]:
library_2020_all.head()

,checkoutmonth,checkouts,checkouttype,checkoutyear,creator,materialtype,publicationyear,publisher,subjects,title,usageclass
0,3,1,Horizon,2020,"Wasserman, Jack, 1921-",BOOK,1984.,"Abrams,",Leonardo da Vinci 1452 1519,Leonardo / text by Jack Wasserman.,Physical
1,3,6,OverDrive,2020,Kassia St. Clair,AUDIOBOOK,2020,HighBridge Company,"Art, Nonfiction",The Golden Thread: How Fabric Changed History ...,Digital
2,3,1,Horizon,2020,"Stamm, Peter, 1963-",BOOK,[2020],"Other Press,","Young women Fiction, Older men Fiction, Fate a...",The sweet indifference of the world / Peter St...,Physical
3,3,32,OverDrive,2020,Charles Duhigg,AUDIOBOOK,2016,Books on Tape,"Business, Nonfiction, Psychology, Self-Improve...",Smarter Faster Better: The Secrets of Being Pr...,Digital
4,3,8,Horizon,2020,"Berrios, Frank",BOOK,2019.,"Random House,","Grumpy Cat Juvenile fiction, Cats Juvenile fic...","Unhappy birthday, Grumpy Cat! / by Frank Berri...",Physical

In [31]:
library_2020_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 639821 entries, 0 to 639820
Data columns (total 11 columns):
checkoutmonth      639821 non-null int64
checkouts          639821 non-null int64
checkouttype       639821 non-null object
checkoutyear       639821 non-null int64
creator            639821 non-null object
materialtype       639821 non-null object
publicationyear    639821 non-null object
publisher          638986 non-null object
subjects           639821 non-null object
title              639821 non-null object
usageclass         639821 non-null object
dtypes: int64(3), object(8)
memory usage: 58.6+ MB

In [18]:
usage_checkouts= library_2020_all.groupby(['usageclass', 'checkoutmonth', 'materialtype'])['checkouts'].sum()

In [35]:
usage_checkouts.unstack()

materialtype              ATLAS  AUDIOBOOK      BOOK     CR     EBOOK     ER  \
usageclass checkoutmonth
Digital    1                NaN   126294.0       NaN    NaN  198356.0    NaN
           2                NaN   117082.0       NaN    NaN  183789.0    NaN
           3                NaN   111031.0       NaN    NaN  210061.0    NaN
Physical   1               29.0        NaN  343328.0  269.0       NaN  151.0
           2               39.0        NaN  317946.0  240.0       NaN  145.0
           3               33.0        NaN  215128.0  191.0       NaN   90.0

materialtype              ER, NONPROJGRAPH  ER, PRINT  ER, SOUNDDISC  \
usageclass checkoutmonth
Digital    1                           NaN        NaN            NaN
           2                           NaN        NaN            NaN
           3                           NaN        NaN            NaN
Physical   1                           3.0        NaN           44.0
           2                           2.0        1.0           60.0
           3                           8.0        1.0           43.0

materialtype              ER, VIDEODISC  ...  SOUNDDISC, SOUNDREC  \
usageclass checkoutmonth                 ...
Digital    1                        NaN  ...                  NaN
           2                        NaN  ...                  NaN
           3                        NaN  ...                  NaN
Physical   1                       75.0  ...                  2.0
           2                       69.0  ...                  2.0
           3                       35.0  ...                  NaN

materialtype              SOUNDDISC, VIDEODISC  SOUNDREC  UNSPECIFIED  VIDEO  \
usageclass checkoutmonth
Digital    1                               NaN       NaN          NaN  166.0
           2                               NaN       NaN          NaN  144.0
           3                               NaN       NaN          NaN  228.0
Physical   1                             263.0     172.0         14.0    NaN
           2                             301.0      93.0         18.0    NaN
           3                             153.0     105.0         12.0    NaN

materialtype              VIDEOCART  VIDEOCASS  VIDEODISC  VIDEOREC  VISUAL
usageclass checkoutmonth
Digital    1                    NaN        NaN        NaN       NaN     NaN
           2                    NaN        NaN        NaN       NaN     NaN
           3                    NaN        NaN        NaN       NaN     NaN
Physical   1                    4.0        7.0   108949.0       1.0    34.0
           2                    5.0        5.0   104503.0       5.0    38.0
           3                    2.0        5.0    60309.0       2.0    17.0

[6 rows x 39 columns]

In [34]:
#Videos too! -Travel related and kids 

library_2020_all[library_2020_all['materialtype']=='VIDEO'].head()

,checkoutmonth,checkouts,checkouttype,checkoutyear,creator,materialtype,publicationyear,publisher,subjects,title,usageclass
271,3,1,OverDrive,2020,International Travel Films,VIDEO,2009,TravelVideoStore.com,"Documentary, Travel",The Great Trans-American Train Ride,Digital
4075,3,1,OverDrive,2020,Connecticut Public Television,VIDEO,2008,Janson Media,Documentary,1964 World's Fair,Digital
5888,3,1,OverDrive,2020,Thich Nhat Hanh,VIDEO,2007,"Sounds True, Inc",Instructional,Mindful Movements,Digital
8645,3,1,OverDrive,2020,Global Television,VIDEO,2008,TravelVideoStore.com,"Documentary, Travel",Meknes Morocco,Digital
8814,3,1,OverDrive,2020,Richard Freeman,VIDEO,2007,"Sounds True, Inc",Instructional,Ashtanga Yoga: The Intermediate Series,Digital

In [36]:
#Higher than Physical!  
library_2020_all.groupby(['usageclass', 'checkoutmonth'])['checkouts'].sum()

usageclass  checkoutmonth
Digital     1                324816
            2                301015
            3                321320
Physical    1                492655
            2                462416
            3                295395
Name: checkouts, dtype: int64

In [6]:
library_2020_all['publicationyear'].value_counts().sort_values(ascending=False)

2019                              28824
2013                              28221
[2019]                            26441
2017                              24358
[2018]                            24308
2014                              22581
2018                              22501
[2017]                            21941
2011                              20786
2015                              20726
2019.                             20302
2016                              18740
[2016]                            18438
2018.                             17080
2012                              16847
[2015]                            15569
2017.                             15249
2016.                             13622
2010                              13138
[2014]                            12856
[2013]                            11558
2015.                             11113
2009                              10907
[2012]                             9984
2014.                              9112
2013.                              8679
[2011]                             8395
2008                               8205
2012.                              8186
[2010]                             7941
                                  ...
[1883]                                1
℗2016                                 1
[2013, p2010]                         1
1998-2000.                            1
[2000], p1984]                        1
2012, ©2006.                          1
[2001, 2003]                          1
[2007, c1999]                         1
[2012], ℗1995.                        1
c1978-c1985.                          1
1886.                                 1
2010, 1910.                           1
1990, [1961]                          1
1922-29.                              1
[2003, p1975]                         1
[between 1983 and 1987].              1
[1972], 1959.                         1
1993, c1992.                          1
2015].                                1
[2002], ©1989.                        1
2017, c2010.                          1
1905-06.                              1
[1973?]                               1
1934-                                 1
2007, 1988.                           1
[1964-66, c1963-64]                   1
Nimbal Publishing, LLC, [2016]        1
1998, 1999.                           1
1892.                                 1
2007 [i.e., 2014].                    1
Name: publicationyear, Length: 2157, dtype: int64

In [43]:
pyear = library_2020_all['publicationyear'].apply(lambda x: re.sub(r'''[\[\]\]\,.;@#?\-\!&$+cp©℗]\ *''', "", x))

In [46]:
pyear.value_counts().sort_values(ascending=False)

1974                216
1970                191
1969                184
1968                174
1965                157
1966                156
1967                146
1964                139
1963                133
1962                120
1960                118
1961                114
1958                106
1959                 95
between 19901999     89
1956                 87
between 19801989     81
20152014             78
20182017             76
1957                 73
20142013             72
1954                 67
1955                 64
20112010             61
1953                 58
20092008             52
1952                 51
1951                 51
1941                 49
20162015             49
20072006             48
20132012             48
1947                 47
1948                 46
20082007             45
1950                 40
1944                 40
20102009             40
1937                 37
1940                 37
20122011             36
between 19001999     36
1943                 36
1949                 35
20192018             34
between 20002009     33
1929                 31
1945                 30
1939                 29
1942                 28
Name: publicationyear, dtype: int64

In [65]:
def is_integer(value: str, *, base: int=10) -> bool:
    try:
        int(value, base=base)
        return True
    except ValueError:
        return False
    
py_bool = pyear.transform(lambda x: is_integer(x))

In [69]:
pyear[py_bool].head()

0    1984
1    2020
2    2020
3    2016
4    2019
Name: publicationyear, dtype: object

In [16]:
mattype = pd.DataFrame(library_2020_all['materialtype'].value_counts().sort_values(ascending=False))

In [94]:
mat_group = library_2020_all[['checkoutmonth','materialtype','checkouts']].groupby(['checkoutmonth', 'checkouts'])['materialtype'].value_counts().sort_values(ascending=False)

In [1]:
subjects.head(25).to_dict()

NameError: name 'subjects' is not defined

In [ ]:
subjects2 = march_details['subjects'].apply(lambda x: pd.value_counts(x.replace(',','').split(" "))).sum(axis = 0)

In [57]:
type(subjects2)

pandas.core.series.Series

In [ ]:
subjects2.sort_values(ascending=False).head(25)

In [27]:
march_details[['usageclass','checkoutmonth','title','subjects','checkouts']].sort_values(by='checkouts', ascending=False).head(100)

,usageclass,checkoutmonth,title,subjects,checkouts
399880,Physical,2,Headphones / Seattle Public Library.,nan,1602
462349,Physical,1,FlexTech--Laptops.,"Laptop computers, iPad Computer, Tablet computers",1558
361517,Physical,2,FlexTech--Laptops.,"Laptop computers, iPad Computer, Tablet computers",1413
194173,Digital,3,There There: A Novel,"Fiction, Literature",1270
626420,Physical,1,Headphones / Seattle Public Library.,nan,995
578862,Physical,1,The Dutch house : a novel / Ann Patchett.,"Brothers and sisters Fiction, Dysfunctional fa...",645
500609,Digital,1,Becoming (Unabridged),"African American Nonfiction, Biography & Autob...",620
39984,Digital,3,Becoming (Unabridged),"African American Nonfiction, Biography & Autob...",617
449030,Digital,1,Becoming,"African American Nonfiction, Biography & Autob...",605
96082,Digital,3,Becoming,"African American Nonfiction, Biography & Autob...",603
526636,Physical,1,Such a fun age : a novel / Kiley Reid.,"Babysitters Fiction, Malicious accusation Fict...",598
403269,Physical,2,SPL HotSpot : connecting Seattle / [distribute...,"Wireless LANs, Wireless Internet, Wireless com...",596
278957,Digital,2,Becoming (Unabridged),"African American Nonfiction, Biography & Autob...",595
613222,Physical,1,Where the crawdads sing / Delia Owens.,"Solitude Fiction, Young women Fiction, Murder ...",594
57769,Digital,3,"Funny, You Don't Look Autistic: A Comedian's G...","Biography & Autobiography, Performing Arts, So...",593
513603,Physical,1,SPL HotSpot : connecting Seattle / [distribute...,"Wireless LANs, Wireless Internet, Wireless com...",592
361331,Digital,2,Becoming,"African American Nonfiction, Biography & Autob...",585
635031,Digital,1,Where the Crawdads Sing,"Fiction, Literature",546
369981,Physical,2,American dirt / Jeanine Cummins.,"Drug traffic Mexico Fiction, Organized crime M...",539
540788,Physical,1,The testaments / Margaret Atwood.,"Surrogate mothers Fiction, Man woman relations...",533
625077,Digital,1,Talking to Strangers: What We Should Know abou...,"Nonfiction, Psychology, Sociology",533
275134,Physical,2,The Dutch house : a novel / Ann Patchett.,"Brothers and sisters Fiction, Dysfunctional fa...",529
523430,Physical,1,"Olive, again / Elizabeth Strout.","Retired teachers Fiction, City and town life F...",523
221194,Digital,2,Where the Crawdads Sing,"Fiction, Literature",522
608293,Digital,1,Educated: A Memoir,"Biography & Autobiography, Nonfiction, Religio...",515
523693,Digital,1,So You Want to Talk about Race (Unabridged),"Nonfiction, Politics, Sociology",514
370671,Physical,2,Such a fun age : a novel / Kiley Reid.,"Babysitters Fiction, Malicious accusation Fict...",498
229273,Digital,2,Educated: A Memoir,"Biography & Autobiography, Nonfiction, Religio...",496
483944,Physical,1,Blue moon / Lee Child.,"Reacher Jack Fictitious character Fiction, Org...",489
58053,Physical,3,FlexTech--Laptops.,"Laptop computers, iPad Computer, Tablet computers",480
...,...,...,...,...,...
429443,Physical,1,The nickel boys : a novel / Colson Whitehead.,"African American teenagers Fiction, Racism Fic...",384
155822,Digital,3,"Crazy Rich Asians: Crazy Rich Asians Series, B...","Fiction, Humor (Fiction), Literature, Romance",383
609836,Physical,1,The overstory : a novel / Richard Powers.,"Trees Fiction, Nature fiction",382
558666,Physical,1,Ninth house / Leigh Bardugo.,"Yale University Fiction, Women college student...",381
595557,Physical,1,"Get a life, Chloe Brown : a novel / Talia Hibb...","Man woman relationships Fiction, Chronically i...",380
369903,Physical,2,"Dear girls : intimate tales, untold secrets, &...","Wong Ali, Comedians United States Biography, W...",373
629238,Digital,1,Educated: A Memoir (unabridged) (Unabridged),"Biography & Autobiography, Nonfiction, Religio...",369
329196,Physical,2,"Blowout : corrupted democracy, rogue state Rus...","Gas industry Corrupt practices, Gas industry C...",366
490057,Physical,1,Maybe you should talk to someone : a therapist...,"Gottlieb Lori Health, Psychotherapists Biograp...",366
471250,Physical,1,Find me / André Aciman.,"Gay men Fiction, Pianists Fiction, College tea...",364
393727,Physical,2,The witches are coming / Lindy West.,Male domination Social structure United States...,362
608147,Digital,1,Where the Crawdads Sing (Unabridged),"Fiction, Literature",361
470504,Physical,1,City of girls / Elizabeth Gilbert.,"Young women Fiction, Theaters Fiction, Enterta...",360
288711,Physical,2,Interior Chinatown / Charles Yu.,"Asian Americans Fiction, Asian Americans in po...",360
243169,Physical,2,The overstory : a novel / Richard Powers.,"Trees Fiction, Nature fiction",359
208606,Digital,2,Educated: A Memoir (unabridged) (Unabridged),"Biography & Autobiography, Nonfiction, Religio...",356
243943,Physical,2,Red at the bone / Jacqueline Woodson.,"Mothers and daughters Fiction, Social classes ...",355
639818,Physical,1,Exhalation / Ted Chiang.,"Science fiction, Short stories",355
238891,Physical,2,How to do nothing : resisting the attention ec...,"Information technology Social aspects, Reflect...",354
609551,Physical,1,Drive your plow over the bones of the dead / O...,"Eccentrics and eccentricities Fiction, Murder ...",352
500841,Physical,1,In the dream house : a memoir / Carmen Maria M...,"Machado Carmen Maria, Women authors American 2...",350
498657,Physical,1,Year of the monkey / Patti Smith.,"Smith Patti, Poets American 20th century Biogr...",348
311778,Physical,2,Floret Farm's a year in flowers : designing go...,"Flower arrangement, Cut flowers, Bouquets",348
380525,Physical,2,Tiny habits : + the small changes that change ...,"Habit, Change Psychology, Self help publications",347
293558,Physical,2,Once upon a time--in Hollywood / Sony ; Columb...,"Television actors and actresses Drama, Stunt p...",340
489697,Physical,1,How to : absurd scientific advice for common r...,"Science Miscellanea, Problem solving",339
228390,Physical,2,"Girl, woman, other / Bernardine Evaristo.","Women Black Great Britain Fiction, Great Brita...",338
568549,Physical,1,Vegetables unleashed : a cookbook / José André...,"Cooking Vegetables, Cookbooks",335
3509,Digital,3,Talking to Strangers: What We Should Know abou...,"Nonfiction, Psychology, Sociology",334
536066,Physical,1,How to be an antiracist / Ibram X. Kendi.,"Kendi Ibram X, Anti racism United States, Raci...",333